# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'bpp-mobile-test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bpp-mobile-test
  pod 'SnapKit', '~> 4.0.0'
  pod 'IQKeyboardManagerSwift', '~> 5.0.8'

  target 'bpp-mobile-testTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble-Snapshots', '~> 6.4.1'
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.3'
  end

end
